language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer install
  - php -S localhost:8080 -t www &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script:
  - curl http://localhost:8080